# Generated by Django 4.2.7 on 2025-06-27 01:50

from django.db import migrations, models
from core.models import Account

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('is_teacher', models.BooleanField(default=False)),
            ],
        ),
    ]
