# Generated by Django 4.2.7 on 2025-07-07 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0002_remove_question_assignment_baitap_cauhoi_course_and_more'),
        ('core', '0004_account_two_factor_enabled_alter_lecture_slide_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teacherapp.course'),
        ),
    ]
