# Generated by Django 5.2.3 on 2025-07-13 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_lecture_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('LOGIN', 'Đăng nhập'), ('LOGOUT', 'Đăng xuất'), ('CREATE', 'Tạo mới'), ('UPDATE', 'Cập nhật'), ('DELETE', 'Xóa'), ('VIEW', 'Xem'), ('BACKUP', 'Sao lưu'), ('RESTORE', 'Phục hồi'), ('SYSTEM', 'Hệ thống')], max_length=20, verbose_name='Loại hành động')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=10, verbose_name='Mức độ')),
                ('message', models.TextField(verbose_name='Thông điệp')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Địa chỉ IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='Chi tiết')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Log Hệ thống',
                'verbose_name_plural': 'Logs Hệ thống',
                'ordering': ['-timestamp'],
            },
        ),
    ]
