# Generated by Django 4.2.7 on 2025-06-27 01:50

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('is_teacher', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, null=True, max_length=254)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=100, blank=True)),
                ('title', models.CharField(max_length=100, blank=True)),
                ('timezone', models.CharField(max_length=50, blank=True)),
                ('phone_number', models.CharField(max_length=20, blank=True)),
                ('avatar', models.ImageField(upload_to='avatars/', blank=True, null=True)),
            ],
        ),
    ]