# Generated by Django 5.2.3 on 2025-07-22 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacherapp', '0006_bailam_nhan_xet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhGiaKhoaHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_danh_gia', models.CharField(choices=[('khoa_hoc', 'Khóa học'), ('bai_tap', 'Bài tập'), ('giang_vien', 'Giảng viên')], default='khoa_hoc', max_length=20)),
                ('diem_sao', models.IntegerField(choices=[(1, '1 sao'), (2, '2 sao'), (3, '3 sao'), (4, '4 sao'), (5, '5 sao')], default=5)),
                ('tieu_de', models.CharField(max_length=200)),
                ('noi_dung', models.TextField()),
                ('gop_y', models.TextField(blank=True, null=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('bai_tap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia_bai_tap', to='teacherapp.baitap')),
                ('sinh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia_sinh_vien', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Đánh giá khóa học',
                'verbose_name_plural': 'Đánh giá khóa học',
                'ordering': ['-ngay_tao'],
            },
        ),
    ]
