# Generated by Django 5.2.3 on 2025-07-22 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_add_khoa_hoc_giang_vien_fields'),
        ('teacherapp', '0006_bailam_nhan_xet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='danhgiakhoahoc',
            name='khoa_hoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia_khoa_hoc', to='teacherapp.course'),
        ),
        migrations.AddField(
            model_name='danhgiakhoahoc',
            name='giang_vien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia_giang_vien', to=settings.AUTH_USER_MODEL),
        ),
    ]
