# Generated by Django 5.2.3 on 2025-07-22 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_auto_20250722_1704'),
        ('teacherapp', '0006_bailam_nhan_xet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThongBao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=200)),
                ('noi_dung', models.TextField()),
                ('loai_thong_bao', models.CharField(choices=[('he_thong', 'Hệ thống'), ('bai_tap', 'Bài tập'), ('khoa_hoc', 'Khóa học'), ('diem_so', 'Điểm số'), ('thi_cu', 'Thi cử'), ('hoc_bong', 'Học bổng'), ('su_kien', 'Sự kiện'), ('thong_bao_chung', 'Thông báo chung')], default='thong_bao_chung', max_length=20)),
                ('muc_do_uu_tien', models.CharField(choices=[('thap', 'Thấp'), ('trung_binh', 'Trung bình'), ('cao', 'Cao'), ('khan_cap', 'Khẩn cấp')], default='trung_binh', max_length=15)),
                ('deadline', models.DateTimeField(blank=True, help_text='Thời hạn nếu có', null=True)),
                ('gui_email', models.BooleanField(default=False, help_text='Gửi thông báo qua email')),
                ('da_gui_email', models.BooleanField(default=False)),
                ('hien_thi', models.BooleanField(default=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('bai_tap_lien_quan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thong_bao_bai_tap', to='teacherapp.baitap')),
                ('khoa_hoc_lien_quan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thong_bao_khoa_hoc', to='teacherapp.course')),
                ('nguoi_tao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thong_bao_da_tao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
                'ordering': ['-ngay_tao'],
            },
        ),
        migrations.CreateModel(
            name='DocThongBao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_doc', models.DateTimeField(auto_now_add=True)),
                ('sinh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thong_bao_da_doc', to=settings.AUTH_USER_MODEL)),
                ('thong_bao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nguoi_da_doc', to='studentapp.thongbao')),
            ],
            options={
                'verbose_name': 'Đọc thông báo',
                'verbose_name_plural': 'Đọc thông báo',
                'unique_together': {('sinh_vien', 'thong_bao')},
            },
        ),
    ]
