# Generated by Django 5.2.3 on 2025-07-22 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0004_thongbao_docthongbao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thongbao',
            name='bai_tap_lien_quan',
        ),
        migrations.RemoveField(
            model_name='thongbao',
            name='khoa_hoc_lien_quan',
        ),
        migrations.RemoveField(
            model_name='thongbao',
            name='nguoi_tao',
        ),
        migrations.DeleteModel(
            name='DocThongBao',
        ),
        migrations.DeleteModel(
            name='ThongBao',
        ),
    ]
