# Generated by Django 5.2.3 on 2025-06-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('teacher', models.CharField(max_length=100)),
                ('tuition', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('schedule', models.CharField(max_length=100)),
                ('num_sessions', models.IntegerField()),
                ('num_attended', models.IntegerField()),
                ('curriculum', models.CharField(max_length=100)),
                ('note', models.TextField()),
                ('num_participants', models.IntegerField()),
            ],
        ),
    ]
