# Generated by Django 5.2.3 on 2025-06-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='num_attended',
        ),
        migrations.RemoveField(
            model_name='course',
            name='num_participants',
        ),
        migrations.RemoveField(
            model_name='course',
            name='num_sessions',
        ),
        migrations.RemoveField(
            model_name='course',
            name='tuition',
        ),
        migrations.AddField(
            model_name='course',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='participants',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='sessions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='curriculum',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='schedule',
            field=models.CharField(max_length=200),
        ),
    ]
