# Generated by Django 5.2.3 on 2025-07-02 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='assignment',
        ),
        migrations.CreateModel(
            name='BaiTap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('mo_ta', models.TextField(verbose_name='Mô tả')),
                ('loai_baitap', models.CharField(choices=[('code', 'Lập trình (Python/Perl)'), ('quiz', 'Trắc nghiệm')], max_length=10, verbose_name='Loại bài tập')),
                ('han_nop', models.DateTimeField(verbose_name='Hạn nộp')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('nguoi_tao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
        ),
        migrations.CreateModel(
            name='CauHoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField(verbose_name='Nội dung câu hỏi')),
                ('lua_chon_a', models.CharField(blank=True, max_length=255, verbose_name='Lựa chọn A')),
                ('lua_chon_b', models.CharField(blank=True, max_length=255, verbose_name='Lựa chọn B')),
                ('lua_chon_c', models.CharField(blank=True, max_length=255, verbose_name='Lựa chọn C')),
                ('lua_chon_d', models.CharField(blank=True, max_length=255, verbose_name='Lựa chọn D')),
                ('dap_an_dung', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Đáp án đúng')),
                ('bai_tap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cau_hoi', to='teacherapp.baitap', verbose_name='Bài tập')),
            ],
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
