# Generated by Django 5.2.3 on 2025-07-11 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0002_remove_question_assignment_baitap_cauhoi_course_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_test', models.CharField(max_length=100)),
                ('input_data', models.TextField()),
                ('expected_output', models.TextField()),
                ('diem_so', models.FloatField(default=1.0)),
                ('bai_tap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='teacherapp.baitap')),
            ],
        ),
        migrations.CreateModel(
            name='BaiLam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_nop', models.DateTimeField(auto_now_add=True)),
                ('diem_so', models.FloatField(blank=True, null=True)),
                ('da_cham', models.BooleanField(default=False)),
                ('dap_an_json', models.JSONField(blank=True, null=True)),
                ('code_nop', models.TextField(blank=True, null=True)),
                ('ket_qua_test', models.JSONField(blank=True, null=True)),
                ('bai_tap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bai_lam', to='teacherapp.baitap')),
                ('sinh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bai_lam', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bài Làm',
                'verbose_name_plural': 'Bài Làm',
                'unique_together': {('sinh_vien', 'bai_tap')},
            },
        ),
    ]
