# Generated by Django 5.2.3 on 2025-07-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0003_testcase_bailam'),
    ]

    operations = [
        migrations.AddField(
            model_name='bailam',
            name='so_cau_dung',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bailam',
            name='so_test_pass',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bailam',
            name='tong_so_cau',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bailam',
            name='tong_so_test',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
