# Generated by Django 5.2.3 on 2025-07-21 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0004_bailam_so_cau_dung_bailam_so_test_pass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bailam',
            name='file_nop',
            field=models.FileField(blank=True, null=True, upload_to='bai_lam/'),
        ),
    ]
