# Generated by Django 5.2.3 on 2025-07-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0005_bailam_file_nop'),
    ]

    operations = [
        migrations.AddField(
            model_name='bailam',
            name='nhan_xet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
