# Generated by Django 5.2.3 on 2025-07-22 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0006_bailam_nhan_xet'),
    ]

    operations = [
        migrations.AddField(
            model_name='baitap',
            name='khoa_hoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bai_tap_list', to='teacherapp.course', verbose_name='Khóa học'),
        ),
    ]
